# Site settings
title: Hackney Development Portal
baseurl: "/ICT Dev Portal" # the subpath of your site, e.g. /blog/
url: "http://jexhson.github.io/jekyll-swagger/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal