swagger: '2.0'
info:
  version: v1
  title: Hackney Addresses API
paths:
  /v1/Addresses/Postcode:
    get:
      tags:
        - Postcode
      summary: Search property details via post code.
      operationId: V1AddressesPostcodeGet
      consumes: []
      produces: []
      parameters:
        - name: postcode
          in: query
          description: The postcode parameter
          required: false
          type: string
        - name: PropertyClassCode
          in: query
          description: Property class code to re-fine search results
          required: false
          type: string
        - name: PropertyClass
          in: query
          description: Textual property class
          required: false
          type: string
        - name: addressStatus
          in: query
          description: 'Address Status for historical/approved addresses, default is Approved Preferred'
          required: false
          type: string
        - name: offset
          in: query
          description: 'For pagination, set the offset of results, index inclusive'
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: 'For pagination, set the amount of results returned'
          required: false
          type: integer
          format: int32
        - name: Format
          in: query
          description: 'To change the return format, from either GIS or Default'
          required: false
          type: string
      responses:
        '200':
          description: Success
  /v1/Addresses/UPRN:
    get:
      tags:
        - UPRN
      summary: Search property details via UPRN.
      operationId: V1AddressesUPRNGet
      consumes: []
      produces: []
      parameters:
        - name: uprn
          in: query
          description: Unique Property Reference Number
          required: false
          type: string
        - name: PropertyClassCode
          in: query
          description: Property class code to re-fine search results
          required: false
          type: string
        - name: PropertyClass
          in: query
          description: Textual property class
          required: false
          type: string
        - name: addressStatus
          in: query
          description: 'Address Status for historical/approved addresses, default is Approved Preferred'
          required: false
          type: string
        - name: offset
          in: query
          description: 'For pagination, set the offset of results, index inclusive'
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: 'For pagination, set the amount of results returned'
          required: false
          type: integer
          format: int32
        - name: Format
          in: query
          description: 'To change the return format, from either GIS or Default'
          required: false
          type: string
      responses:
        '200':
          description: Success
  /v1/Addresses/USRN:
    get:
      tags:
        - USRN
      summary: Search property details via USRN.
      operationId: V1AddressesUSRNGet
      consumes: []
      produces: []
      parameters:
        - name: usrn
          in: query
          description: Unique Street Reference Number
          required: false
          type: string
        - name: PropertyClassCode
          in: query
          description: Property class code to re-fine search results
          required: false
          type: string
        - name: PropertyClass
          in: query
          description: Textual property class
          required: false
          type: string
        - name: addressStatus
          in: query
          description: 'Address Status for historical/approved addresses, default is Approved Preferred'
          required: false
          type: string
        - name: offset
          in: query
          description: 'For pagination, set the offset of results, index inclusive'
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: 'For pagination, set the amount of results returned'
          required: false
          type: integer
          format: int32
        - name: Format
          in: query
          description: 'To change the return format, from either GIS or Default'
          required: false
          type: string
      responses:
        '200':
          description: Success
  /api/Values:
    get:
      tags:
        - Values
      operationId: ApiValuesGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              type: string
    post:
      tags:
        - Values
      operationId: ApiValuesPost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: value
          in: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
  '/api/Values/{id}':
    get:
      tags:
        - Values
      operationId: ApiValuesByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            type: string
    put:
      tags:
        - Values
      operationId: ApiValuesByIdPut
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: value
          in: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Values
      operationId: ApiValuesByIdDelete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
definitions: {}
securityDefinitions: {}
